#pragma once

#include <QHash>
#include <QString>

enum class DrumsetsSamples {
    china,
    china_stereo,
    crash_1,
    crash_1_stereo,
    crash_2,
    crash_2_stereo,
    crash_3,
    crash_3_stereo,
    hand_clap,
    hand_clap_stereo,
    hh_close_from_open,
    hh_close_from_open_stereo,
    hh_closed,
    hh_closed_stereo,
    hh_foot,
    hh_foot_stereo,
    hh_open,
    hh_open_stereo,
    kick,
    kick_stereo,
    ride_bell,
    ride_bell_stereo,
    ride,
    ride_stereo,
    snare_rim,
    snare_rim_stereo,
    snare_sidestick,
    snare_sidestick_stereo,
    snare_snares_off_rim,
    snare_snares_off_rim_stereo,
    snare_snares_off_sidestick,
    snare_snares_off_sidestick_stereo,
    snare_snares_off,
    snare_snares_off_stereo,
    snare,
    snare_stereo,
    splash,
    splash_stereo,
    stick_click,
    stick_click_stereo,
    tom_1_rim,
    tom_1_rim_stereo,
    tom_1,
    tom_1_stereo,
    tom_2_rim,
    tom_2_rim_stereo,
    tom_2,
    tom_2_stereo,
    tom_3_rim,
    tom_3_rim_stereo,
    tom_3,
    tom_3_stereo,
};

inline const QHash<DrumsetsSamples, QString> DrumsetsSampleFiles = {
    { DrumsetsSamples::china, "gretschDrumset_china" },
    { DrumsetsSamples::china_stereo, "gretschDrumset_china_stereo" },
    { DrumsetsSamples::crash_1, "gretschDrumset_crash 1" },
    { DrumsetsSamples::crash_1_stereo, "gretschDrumset_crash 1_stereo" },
    { DrumsetsSamples::crash_2, "gretschDrumset_crash 2" },
    { DrumsetsSamples::crash_2_stereo, "gretschDrumset_crash 2_stereo" },
    { DrumsetsSamples::crash_3, "gretschDrumset_crash 3" },
    { DrumsetsSamples::crash_3_stereo, "gretschDrumset_crash 3_stereo" },
    { DrumsetsSamples::hand_clap, "gretschDrumset_hand clap" },
    { DrumsetsSamples::hand_clap_stereo, "gretschDrumset_hand clap_stereo" },
    { DrumsetsSamples::hh_close_from_open, "gretschDrumset_hh close from open" },
    { DrumsetsSamples::hh_close_from_open_stereo, "gretschDrumset_hh close from open_stereo" },
    { DrumsetsSamples::hh_closed, "gretschDrumset_hh closed" },
    { DrumsetsSamples::hh_closed_stereo, "gretschDrumset_hh closed_stereo" },
    { DrumsetsSamples::hh_foot, "gretschDrumset_hh foot" },
    { DrumsetsSamples::hh_foot_stereo, "gretschDrumset_hh foot_stereo" },
    { DrumsetsSamples::hh_open, "gretschDrumset_hh open" },
    { DrumsetsSamples::hh_open_stereo, "gretschDrumset_hh open_stereo" },
    { DrumsetsSamples::kick, "gretschDrumset_kick" },
    { DrumsetsSamples::kick_stereo, "gretschDrumset_kick_stereo" },
    { DrumsetsSamples::ride_bell, "gretschDrumset_ride bell" },
    { DrumsetsSamples::ride_bell_stereo, "gretschDrumset_ride bell_stereo" },
    { DrumsetsSamples::ride, "gretschDrumset_ride" },
    { DrumsetsSamples::ride_stereo, "gretschDrumset_ride_stereo" },
    { DrumsetsSamples::snare_rim, "gretschDrumset_snare rim" },
    { DrumsetsSamples::snare_rim_stereo, "gretschDrumset_snare rim_stereo" },
    { DrumsetsSamples::snare_sidestick, "gretschDrumset_snare sidestick" },
    { DrumsetsSamples::snare_sidestick_stereo, "gretschDrumset_snare sidestick_stereo" },
    { DrumsetsSamples::snare_snares_off_rim, "gretschDrumset_snare snares off rim" },
    { DrumsetsSamples::snare_snares_off_rim_stereo, "gretschDrumset_snare snares off rim_stereo" },
    { DrumsetsSamples::snare_snares_off_sidestick, "gretschDrumset_snare snares off sidestick" },
    { DrumsetsSamples::snare_snares_off_sidestick_stereo, "gretschDrumset_snare snares off sidestick_stereo" },
    { DrumsetsSamples::snare_snares_off, "gretschDrumset_snare snares off" },
    { DrumsetsSamples::snare_snares_off_stereo, "gretschDrumset_snare snares off_stereo" },
    { DrumsetsSamples::snare, "gretschDrumset_snare" },
    { DrumsetsSamples::snare_stereo, "gretschDrumset_snare_stereo" },
    { DrumsetsSamples::splash, "gretschDrumset_splash" },
    { DrumsetsSamples::splash_stereo, "gretschDrumset_splash_stereo" },
    { DrumsetsSamples::stick_click, "gretschDrumset_stick click" },
    { DrumsetsSamples::stick_click_stereo, "gretschDrumset_stick click_stereo" },
    { DrumsetsSamples::tom_1_rim, "gretschDrumset_tom 1 rim" },
    { DrumsetsSamples::tom_1_rim_stereo, "gretschDrumset_tom 1 rim_stereo" },
    { DrumsetsSamples::tom_1, "gretschDrumset_tom 1" },
    { DrumsetsSamples::tom_1_stereo, "gretschDrumset_tom 1_stereo" },
    { DrumsetsSamples::tom_2_rim, "gretschDrumset_tom 2 rim" },
    { DrumsetsSamples::tom_2_rim_stereo, "gretschDrumset_tom 2 rim_stereo" },
    { DrumsetsSamples::tom_2, "gretschDrumset_tom 2" },
    { DrumsetsSamples::tom_2_stereo, "gretschDrumset_tom 2_stereo" },
    { DrumsetsSamples::tom_3_rim, "gretschDrumset_tom 3 rim" },
    { DrumsetsSamples::tom_3_rim_stereo, "gretschDrumset_tom 3 rim_stereo" },
    { DrumsetsSamples::tom_3, "gretschDrumset_tom 3" },
    { DrumsetsSamples::tom_3_stereo, "gretschDrumset_tom 3_stereo" },
};

