#pragma once
#include <QHash>
#include <QString>
// existing contents...
enum class SynthesizersSamples {
    None,
    Sample12_String,
    Sample6_String,
    Ac_Bass,
    Aftertouch,
    Ahh,
    Al_s_Rhodes,
    Analog_Brass,
    Arrangement,
    Bellery,
    Bowed_String,
    Cellos,
    Clarinet,
    Club_Piano,
    Crockett_s,
    Deep_Purple,
    Desmos_GraphingCalcSynth_Wavetable,
    Digi_Piano,
    Dragon_Hall,
    Electric_Bass,
    Flute,
    French_Horn,
    Fuzz_Clav,
    Glocken,
    Gong_of_Kings,
    Harpsichord,
    Heavy_Hitter,
    Jan_s_Theme,
    Jazz_Harp,
    Jazz_Organ,
    Kick_Bass,
    Kimono,
    Marimba,
    Music_Box,
    Nasty_Brass,
    Oboe,
    Ole_,
    Orchestra,
    Pan_Flute,
    Piano_1,
    Piano_2,
    Pizzicato,
    Pull_Bass,
    Reflection,
    Return_Home,
    Saxy,
    Sitar,
    Steel_Drums,
    Steel_Keys,
    Stratocaster,
    String_Ens,
    String_Pad,
    StrutNstuff,
    Terminator,
    Trumpet,
    Visitors,
    Voice,
    Vybes,
};

inline const QHash<SynthesizersSamples, QString> SynthesizersSampleFiles = {
    { SynthesizersSamples::Sample12_String, "12 String" },
    { SynthesizersSamples::Sample6_String, "6 String" },
    { SynthesizersSamples::Ac_Bass, "Ac Bass" },
    { SynthesizersSamples::Aftertouch, "Aftertouch" },
    { SynthesizersSamples::Ahh, "Ahh" },
    { SynthesizersSamples::Al_s_Rhodes, "Al's Rhodes" },
    { SynthesizersSamples::Analog_Brass, "Analog Brass" },
    { SynthesizersSamples::Arrangement, "Arrangement" },
    { SynthesizersSamples::Bellery, "Bellery" },
    { SynthesizersSamples::Bowed_String, "Bowed String" },
    { SynthesizersSamples::Cellos, "Cellos" },
    { SynthesizersSamples::Clarinet, "Clarinet" },
    { SynthesizersSamples::Club_Piano, "Club Piano" },
    { SynthesizersSamples::Crockett_s, "Crockett's" },
    { SynthesizersSamples::Deep_Purple, "Deep Purple" },
    { SynthesizersSamples::Desmos_GraphingCalcSynth_Wavetable, "Desmos_GraphingCalcSynth_Wavetable" },
    { SynthesizersSamples::Digi_Piano, "Digi Piano" },
    { SynthesizersSamples::Dragon_Hall, "Dragon Hall" },
    { SynthesizersSamples::Electric_Bass, "Electric Bass" },
    { SynthesizersSamples::Flute, "Flute" },
    { SynthesizersSamples::French_Horn, "French Horn" },
    { SynthesizersSamples::Fuzz_Clav, "Fuzz Clav" },
    { SynthesizersSamples::Glocken, "Glocken" },
    { SynthesizersSamples::Gong_of_Kings, "Gong of Kings" },
    { SynthesizersSamples::Harpsichord, "Harpsichord" },
    { SynthesizersSamples::Heavy_Hitter, "Heavy Hitter" },
    { SynthesizersSamples::Jan_s_Theme, "Jan's Theme" },
    { SynthesizersSamples::Jazz_Harp, "Jazz Harp" },
    { SynthesizersSamples::Jazz_Organ, "Jazz Organ" },
    { SynthesizersSamples::Kick_Bass, "Kick Bass" },
    { SynthesizersSamples::Kimono, "Kimono" },
    { SynthesizersSamples::Marimba, "Marimba" },
    { SynthesizersSamples::Music_Box, "Music Box" },
    { SynthesizersSamples::Nasty_Brass, "Nasty Brass" },
    { SynthesizersSamples::Oboe, "Oboe" },
    { SynthesizersSamples::Ole_, "Ole!" },
    { SynthesizersSamples::Orchestra, "Orchestra" },
    { SynthesizersSamples::Pan_Flute, "Pan Flute" },
    { SynthesizersSamples::Piano_1, "Piano 1" },
    { SynthesizersSamples::Piano_2, "Piano 2" },
    { SynthesizersSamples::Pizzicato, "Pizzicato" },
    { SynthesizersSamples::Pull_Bass, "Pull Bass" },
    { SynthesizersSamples::Reflection, "Reflection" },
    { SynthesizersSamples::Return_Home, "Return Home" },
    { SynthesizersSamples::Saxy, "Saxy" },
    { SynthesizersSamples::Sitar, "Sitar" },
    { SynthesizersSamples::Steel_Drums, "Steel Drums" },
    { SynthesizersSamples::Steel_Keys, "Steel Keys" },
    { SynthesizersSamples::Stratocaster, "Stratocaster" },
    { SynthesizersSamples::String_Ens, "String Ens" },
    { SynthesizersSamples::String_Pad, "String Pad" },
    { SynthesizersSamples::StrutNstuff, "StrutNstuff" },
    { SynthesizersSamples::Terminator, "Terminator" },
    { SynthesizersSamples::Trumpet, "Trumpet" },
    { SynthesizersSamples::Visitors, "Visitors" },
    { SynthesizersSamples::Voice, "Voice" },
    { SynthesizersSamples::Vybes, "Vybes" },
};
